version: "3.0"
services:

  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: datacatalog
      POSTGRES_USER: datacatalog
      POSTGRES_PASSWORD: datacatalog

  api:
    build:
      context: .
    image: amsterdam/dcatd:latest
    depends_on:
      - database
      - builder
    volumes:
      - ./examples/running/config.yml:/etc/dcatd.yml
    ports:
      - "8122:8000"
    environment:
      DB_DATABASE: datacatalog
      DB_USER: datacatalog
      DB_PASSWORD: datacatalog
      DB_HOST: database
      DB_PORT: 5432
    command: ["python", "-m", "datacatalog.main"]

  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: amsterdam/dcatd-builder:latest
    depends_on:
      - database
    environment:
      DB_DATABASE: datacatalog
      DB_USER: datacatalog
      DB_PASSWORD: datacatalog
      DB_HOST: database
      DB_PORT: 5432
    command: ["make", "test"]
