version: "3.0"
services:

  database:
    image: postgres:9.5
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: datacatalog
      POSTGRES_USER: datacatalog
      POSTGRES_PASSWORD: datacatalog

  example:
    build:
      context: .
    depends_on:
      - database
    volumes:
      - ./examples/running/config.yml:/etc/dcatd.yml
    ports:
      - "8000:8000"
    environment:
      DB_DATABASE: datacatalog
      DB_USER: datacatalog
      DB_PASSWORD: datacatalog
      DB_HOST: database
      DB_PORT: 5432
      SWIFT_PASSWORD: insecure
      SWIFT_CONTAINER: dcatd_acc
    command: ["python", "-m", "datacatalog.main"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - database
    environment:
      DB_DATABASE: datacatalog
      DB_USER: datacatalog
      DB_PASSWORD: datacatalog
      DB_HOST: database
      DB_PORT: 5432
      SWIFT_PASSWORD: insecure
      SWIFT_CONTAINER: dcatd_acc
    command: ["make", "test"]

  swaggerui:
    image: amsterdam/oauth2swaggerui
    ports:
      - 8686:8686
