$schema: 'http://json-schema.org/draft-07/schema#'

type: object

properties:
  logging:
    $ref: '#/definitions/logging.dictconfig'
  plugins:
    $ref: '#/definitions/plugins'
  web:
    $ref: '#/definitions/web'
  jwks:
    $ref: '#/definitions/jwks'
  cors:
    $ref: '#/definitions/cors'
  primarySchema:
    type: string
    # URL-segment safe string:
    pattern: "^(?:%[a-f0-9]{2}|[-\\w:@!$&'()*+,;=.~])*$"

required:
- logging
- plugins
- primarySchema
- web


definitions:

  plugins:
    type: array
    items:
      type: string
      pattern: '^((?:[_a-zA-Z][\w]*\.)+)([_a-zA-Z][\w]*)$'

  web:
    additionalProperties: false
    properties:
      port:
        type: integer
        minimum: 1024
        maximum: 65535
      baseurl:
        type: string
        pattern: '/$'
      allow_cors:
        type: boolean
        default: false
    required:
    - port
    - baseurl
    type: object

  jwks:
    type: string

  allowed_signing_algorithms:
    type: array
    items:
      type: string

  cors:
    type: object
    additionalProperties: false
    properties:
      allow_all:
        type: boolean


  logging.dictconfig:
    additionalProperties: false
    properties:
      disable_existing_loggers:
        type: boolean
      filters:
        patternProperties:
          ^[a-zA-Z0-9._-]+$:
            additionalProperties: false
            properties:
              name:
                type: string
            type: object
        type: object
      formatters:
        patternProperties:
          '^[a-zA-Z0-9._-]+$':
            additionalProperties: false
            properties:
              datefmt:
                type: string
              format:
                type: string
            type: object
        type: object
      handlers:
        patternProperties:
          '^[a-zA-Z0-9._-]+$':
            properties:
              class:
                type: string
              filters:
                items:
                  type: string
                type: array
                uniqueItems: true
              formatter:
                type: string
              level:
                type: string
            required:
              - class
            type: object
        type: object
      incremental:
        type: boolean
      loggers:
        patternProperties:
          ^[a-zA-Z0-9._-]+$:
            properties:
              filters:
                items:
                  type: string
                type: array
                uniqueItems: true
              handlers:
                items:
                  type: string
                type: array
                uniqueItems: true
              level:
                type: string
              propagate:
                type: boolean
            type: object
        type: object
      root:
        properties:
          filters:
            items:
              type: string
            type: array
            uniqueItems: true
          handlers:
            items:
              type: string
            type: array
            uniqueItems: true
          level:
            enum:
              - CRITICAL
              - ERROR
              - WARNING
              - INFO
              - DEBUG
            type: string
        type: object
      version:
        enum:
          - 1
        type: integer
    required:
      - version
    type: object
